#
# Make macros form Spectrum target
# 

# Start addresses for code, data and stack.
# If you change these, you may also want to change
# the memory settings in config.h
CODE_ADDR=0x0000
DATA_ADDR=0x5b00
STACK_ADDR=0xffff

include $(TOPDIR)/config/Makefile.sdcc

CFLAGS += -DARCH_SPECTRUM

